title: Formal power series, and applications (2026-2027)
description: tuesdays 16:15-17:45 (lecture) / 18:15-19:45 (tutorial), room 3140@MIMUW

repository: lclem/FPS_2026_2027
branch: main

baseurl: "/FPS_2026_2027"
url: "https://lclem.github.io/FPS_2026_2027/"

class: title, shelf, no-footer, fullbleed

# theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0

last_updated: true
markdown: kramdown

layouts_dir: _layouts
includes_dir: _includes

encoding: "utf-8"
show_dir_listing: false

plugins:
  - jekyll-pdf-embed
  - jekyll-last-modified-at
  - jekyll-scholar
  - jekyll-remote-theme

include: ["_pages", "tutorials/build"]

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - Makefile
  - README.md
  - update.sh
  - tutorials/*.tex
  - tutorials/Makefile

scholar:
  # style: modern-language-association
  style: apa
  # style: assets/natbib.csl
  locale: en
  source: ./_bibliography
  bibliography: references.bib

github:
  is_project_page: false