source 'https://rubygems.org'
#gem "jekyll-theme-example"

group :jekyll_plugins do	
	gem "github-pages"
	gem "jekyll-theme-slate"
	gem "jekyll-last-modified-at"
	gem 'jekyll-scholar'
end

gem "faraday-retry"
gem "bigdecimal"
gem "csv"

gem "webrick", "~> 1.9"
